# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(481, 337)
        MainWindow.setWindowOpacity(0.97)
        MainWindow.setStyleSheet("background-color: rgb(255, 220, 244);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(-1, -1, -1, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 2, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.tabWidget.setFont(font)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(12, 12))
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab1 = QtWidgets.QWidget()
        self.tab1.setObjectName("tab1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.record_button_manage = QtWidgets.QPushButton(self.tab1)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setBold(False)
        font.setWeight(50)
        self.record_button_manage.setFont(font)
        self.record_button_manage.setStyleSheet("border-color: rgb(0, 0, 101);\n"
"background-color: rgb(255, 149, 206);")
        self.record_button_manage.setAutoRepeatDelay(240)
        self.record_button_manage.setAutoRepeatInterval(70)
        self.record_button_manage.setObjectName("record_button_manage")
        self.gridLayout_2.addWidget(self.record_button_manage, 5, 0, 1, 1)
        self.record_button_delete = QtWidgets.QPushButton(self.tab1)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setBold(False)
        font.setWeight(50)
        self.record_button_delete.setFont(font)
        self.record_button_delete.setStyleSheet("border-color: rgb(0, 0, 101);\n"
"background-color: rgb(255, 149, 206);")
        self.record_button_delete.setAutoRepeatDelay(240)
        self.record_button_delete.setAutoRepeatInterval(70)
        self.record_button_delete.setObjectName("record_button_delete")
        self.gridLayout_2.addWidget(self.record_button_delete, 5, 2, 1, 1)
        self.record_button_save = QtWidgets.QPushButton(self.tab1)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setBold(False)
        font.setWeight(50)
        self.record_button_save.setFont(font)
        self.record_button_save.setStyleSheet("border-color: rgb(0, 0, 101);\n"
"background-color: rgb(255, 149, 206);")
        self.record_button_save.setAutoRepeatDelay(240)
        self.record_button_save.setAutoRepeatInterval(70)
        self.record_button_save.setObjectName("record_button_save")
        self.gridLayout_2.addWidget(self.record_button_save, 5, 3, 1, 1)
        self.record_button_record = QtWidgets.QPushButton(self.tab1)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setBold(False)
        font.setWeight(50)
        self.record_button_record.setFont(font)
        self.record_button_record.setStyleSheet("border-color: rgb(0, 0, 101);\n"
"background-color: rgb(255, 149, 206);")
        self.record_button_record.setAutoRepeatDelay(240)
        self.record_button_record.setAutoRepeatInterval(70)
        self.record_button_record.setObjectName("record_button_record")
        self.gridLayout_2.addWidget(self.record_button_record, 5, 1, 1, 1)
        self.frame = QtWidgets.QFrame(self.tab1)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_3.setContentsMargins(-1, -1, -1, 0)
        self.gridLayout_3.setHorizontalSpacing(5)
        self.gridLayout_3.setVerticalSpacing(8)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.record_text_meaning = QtWidgets.QPlainTextEdit(self.frame)
        self.record_text_meaning.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.record_text_meaning.setStyleSheet("background-color: rgb(238, 242, 255);")
        self.record_text_meaning.setTabChangesFocus(True)
        self.record_text_meaning.setObjectName("record_text_meaning")
        self.gridLayout_3.addWidget(self.record_text_meaning, 1, 2, 1, 1)
        self.record_label_meaing = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.record_label_meaing.setFont(font)
        self.record_label_meaing.setStyleSheet("color: rgb(0, 73, 221);")
        self.record_label_meaing.setObjectName("record_label_meaing")
        self.gridLayout_3.addWidget(self.record_label_meaing, 1, 0, 1, 1)
        self.record_text_example = QtWidgets.QPlainTextEdit(self.frame)
        self.record_text_example.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.record_text_example.setStyleSheet("background-color: rgb(238, 242, 255);")
        self.record_text_example.setFrameShape(QtWidgets.QFrame.Box)
        self.record_text_example.setTabChangesFocus(True)
        self.record_text_example.setObjectName("record_text_example")
        self.gridLayout_3.addWidget(self.record_text_example, 2, 2, 1, 1)
        self.record_label_example = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.record_label_example.setFont(font)
        self.record_label_example.setStyleSheet("color: rgb(0, 73, 221);")
        self.record_label_example.setObjectName("record_label_example")
        self.gridLayout_3.addWidget(self.record_label_example, 2, 0, 1, 1)
        self.record_label_words = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.record_label_words.setFont(font)
        self.record_label_words.setStyleSheet("color: rgb(0, 73, 221);")
        self.record_label_words.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.record_label_words.setObjectName("record_label_words")
        self.gridLayout_3.addWidget(self.record_label_words, 0, 0, 1, 1)
        self.record_label_status = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setStrikeOut(False)
        self.record_label_status.setFont(font)
        self.record_label_status.setStyleSheet("color: rgb(170, 85, 255)")
        self.record_label_status.setAlignment(QtCore.Qt.AlignCenter)
        self.record_label_status.setObjectName("record_label_status")
        self.gridLayout_3.addWidget(self.record_label_status, 3, 0, 1, 3)
        self.record_text_word = QtWidgets.QLineEdit(self.frame)
        self.record_text_word.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.record_text_word.setStyleSheet("background-color: rgb(238, 242, 255);")
        self.record_text_word.setObjectName("record_text_word")
        self.gridLayout_3.addWidget(self.record_text_word, 0, 2, 1, 1)
        self.gridLayout_3.setRowStretch(0, 2)
        self.gridLayout_3.setRowStretch(1, 2)
        self.gridLayout_3.setRowStretch(2, 4)
        self.gridLayout_3.setRowStretch(3, 1)
        self.gridLayout_2.addWidget(self.frame, 1, 0, 2, 4)
        self.tabWidget.addTab(self.tab1, "")
        self.tab2 = QtWidgets.QWidget()
        self.tab2.setObjectName("tab2")
        self.tabWidget.addTab(self.tab2, "")
        self.tab3 = QtWidgets.QWidget()
        self.tab3.setObjectName("tab3")
        self.tabWidget.addTab(self.tab3, "")
        self.tab4 = QtWidgets.QWidget()
        self.tab4.setObjectName("tab4")
        self.tabWidget.addTab(self.tab4, "")
        self.tab5 = QtWidgets.QWidget()
        self.tab5.setObjectName("tab5")
        self.tabWidget.addTab(self.tab5, "")
        self.tab6 = QtWidgets.QWidget()
        self.tab6.setObjectName("tab6")
        self.tabWidget.addTab(self.tab6, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tabWidget, self.record_text_word)
        MainWindow.setTabOrder(self.record_text_word, self.record_text_meaning)
        MainWindow.setTabOrder(self.record_text_meaning, self.record_text_example)
        MainWindow.setTabOrder(self.record_text_example, self.record_button_manage)
        MainWindow.setTabOrder(self.record_button_manage, self.record_button_record)
        MainWindow.setTabOrder(self.record_button_record, self.record_button_delete)
        MainWindow.setTabOrder(self.record_button_delete, self.record_button_save)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Powered by Hoshino Koji, 2020."))
        self.record_button_manage.setText(_translate("MainWindow", "管理单词本(M)..."))
        self.record_button_manage.setShortcut(_translate("MainWindow", "Alt+M"))
        self.record_button_delete.setText(_translate("MainWindow", "撤销(C)"))
        self.record_button_delete.setShortcut(_translate("MainWindow", "Alt+C"))
        self.record_button_save.setText(_translate("MainWindow", "保存(S)"))
        self.record_button_save.setShortcut(_translate("MainWindow", "Alt+S"))
        self.record_button_record.setText(_translate("MainWindow", "录入(R)"))
        self.record_button_record.setShortcut(_translate("MainWindow", "Alt+R"))
        self.record_label_meaing.setText(_translate("MainWindow", "释义"))
        self.record_label_example.setText(_translate("MainWindow", "例句"))
        self.record_label_words.setText(_translate("MainWindow", "单词"))
        self.record_label_status.setText(_translate("MainWindow", "当前状态：无"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), _translate("MainWindow", "录入"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab2), _translate("MainWindow", "复习"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab3), _translate("MainWindow", "管理"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab4), _translate("MainWindow", "命令行"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab5), _translate("MainWindow", "帮助"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab6), _translate("MainWindow", "About..."))
